"""Add missing columns to Quiz and Submission

Revision ID: a376947820e1
Revises: 08cf2291b824
Create Date: 2026-03-23 03:02:20.981062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a376947820e1'
down_revision: Union[str, None] = '08cf2291b824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('submissions', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('submissions', sa.Column('os', sa.String(length=100), nullable=True))
    op.add_column('submissions', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'location')
    op.drop_column('submissions', 'os')
    op.drop_column('submissions', 'browser')
    op.drop_column('submissions', 'user_agent')
    op.drop_column('submissions', 'ip_address')
    op.drop_column('quizzes', 'max_attempts')
    # ### end Alembic commands ###
